grpc:
  client:
    payment-service:
      address: static://payment-service:9094
      negotiationType: plaintext
    order-service:
      address: static://order-service:9091
      negotiationType: plaintext
server:
  port: 8081