spring:
  application:
    name: filestorage-app

  datasource:
      url: jdbc:postgresql://filestorage-db:5432/file_db
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
      #      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yaml
server:

  port: 8083
grpc:
  server:
    port: 9091